// Index of every country and major territory travellers search for.
//
// Used to recognise any real destination in search (including native names, former names
// and typos) and to route Schengen members to the Schengen rule. This index carries no visa
// rules: those live in lib/visa/data/<passport>.ts.
//
// Covers all 193 UN member states, the two UN observer states (Holy See, Palestine), Taiwan,
// Kosovo, and major inhabited territories with their own entry rules.

import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // South Asia
  { code: "AF", name: "Afghanistan", region: "South Asia" },
  { code: "BD", name: "Bangladesh", region: "South Asia" },
  { code: "BT", name: "Bhutan", region: "South Asia" },
  { code: "IN", name: "India", region: "South Asia", aliases: ["Bharat"] },
  { code: "MV", name: "Maldives", region: "South Asia" },
  { code: "NP", name: "Nepal", region: "South Asia" },
  { code: "PK", name: "Pakistan", region: "South Asia" },
  { code: "LK", name: "Sri Lanka", region: "South Asia", aliases: ["Ceylon"] },

  // Southeast Asia
  { code: "BN", name: "Brunei", region: "Southeast Asia", aliases: ["Brunei Darussalam"] },
  { code: "KH", name: "Cambodia", region: "Southeast Asia" },
  { code: "ID", name: "Indonesia", region: "Southeast Asia", cities: ["Jakarta", "Bali"] },
  { code: "LA", name: "Laos", region: "Southeast Asia", aliases: ["Lao PDR"] },
  { code: "MY", name: "Malaysia", region: "Southeast Asia" },
  { code: "MM", name: "Myanmar", region: "Southeast Asia", aliases: ["Burma"] },
  { code: "PH", name: "Philippines", region: "Southeast Asia" },
  { code: "SG", name: "Singapore", region: "Southeast Asia" },
  { code: "TH", name: "Thailand", region: "Southeast Asia" },
  { code: "TL", name: "Timor-Leste", region: "Southeast Asia", aliases: ["East Timor"] },
  { code: "VN", name: "Vietnam", region: "Southeast Asia", aliases: ["Viet Nam"] },

  // East Asia
  { code: "CN", name: "China", region: "East Asia" },
  { code: "HK", name: "Hong Kong", region: "East Asia", territoryOf: "CN" },
  { code: "JP", name: "Japan", region: "East Asia" },
  { code: "MO", name: "Macau", region: "East Asia", aliases: ["Macao"], territoryOf: "CN" },
  { code: "MN", name: "Mongolia", region: "East Asia" },
  { code: "KP", name: "North Korea", region: "East Asia" },
  { code: "KR", name: "South Korea", region: "East Asia", aliases: ["Korea"] },
  { code: "TW", name: "Taiwan", region: "East Asia" },

  // Central Asia
  { code: "KZ", name: "Kazakhstan", region: "Central Asia" },
  { code: "KG", name: "Kyrgyzstan", region: "Central Asia" },
  { code: "TJ", name: "Tajikistan", region: "Central Asia" },
  { code: "TM", name: "Turkmenistan", region: "Central Asia" },
  { code: "UZ", name: "Uzbekistan", region: "Central Asia" },

  // Caucasus
  { code: "AM", name: "Armenia", region: "Caucasus" },
  { code: "AZ", name: "Azerbaijan", region: "Caucasus" },
  { code: "GE", name: "Georgia", region: "Caucasus" },

  // Middle East
  { code: "BH", name: "Bahrain", region: "Middle East" },
  { code: "IR", name: "Iran", region: "Middle East", aliases: ["Persia"] },
  { code: "IQ", name: "Iraq", region: "Middle East" },
  { code: "IL", name: "Israel", region: "Middle East" },
  { code: "JO", name: "Jordan", region: "Middle East" },
  { code: "KW", name: "Kuwait", region: "Middle East" },
  { code: "LB", name: "Lebanon", region: "Middle East" },
  { code: "OM", name: "Oman", region: "Middle East" },
  { code: "PS", name: "Palestine", region: "Middle East", aliases: ["State of Palestine"] },
  { code: "QA", name: "Qatar", region: "Middle East" },
  { code: "SA", name: "Saudi Arabia", region: "Middle East" },
  { code: "SY", name: "Syria", region: "Middle East" },
  { code: "TR", name: "Türkiye", region: "Middle East", aliases: ["Turkey"] },
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Middle East",
    aliases: ["UAE", "Emirates"],
    cities: ["Dubai", "Abu Dhabi"],
  },
  { code: "YE", name: "Yemen", region: "Middle East" },

  // Europe
  { code: "AL", name: "Albania", region: "Europe" },
  { code: "AD", name: "Andorra", region: "Europe" },
  { code: "AT", name: "Austria", region: "Europe", schengen: true },
  { code: "BY", name: "Belarus", region: "Europe" },
  { code: "BE", name: "Belgium", region: "Europe", schengen: true },
  { code: "BA", name: "Bosnia and Herzegovina", region: "Europe" },
  { code: "BG", name: "Bulgaria", region: "Europe", schengen: true },
  { code: "HR", name: "Croatia", region: "Europe", schengen: true },
  { code: "CY", name: "Cyprus", region: "Europe" },
  { code: "CZ", name: "Czechia", region: "Europe", schengen: true, aliases: ["Czech Republic", "Česko"] },
  { code: "DK", name: "Denmark", region: "Europe", schengen: true },
  { code: "EE", name: "Estonia", region: "Europe", schengen: true },
  { code: "FI", name: "Finland", region: "Europe", schengen: true },
  { code: "FR", name: "France", region: "Europe", schengen: true, cities: ["Paris"] },
  { code: "DE", name: "Germany", region: "Europe", schengen: true, aliases: ["Deutschland"] },
  { code: "GR", name: "Greece", region: "Europe", schengen: true },
  { code: "HU", name: "Hungary", region: "Europe", schengen: true },
  { code: "IS", name: "Iceland", region: "Europe", schengen: true },
  { code: "IE", name: "Ireland", region: "Europe" },
  { code: "IT", name: "Italy", region: "Europe", schengen: true, aliases: ["Italia"] },
  { code: "XK", name: "Kosovo", region: "Europe" },
  { code: "LV", name: "Latvia", region: "Europe", schengen: true },
  { code: "LI", name: "Liechtenstein", region: "Europe", schengen: true },
  { code: "LT", name: "Lithuania", region: "Europe", schengen: true },
  { code: "LU", name: "Luxembourg", region: "Europe", schengen: true },
  { code: "MT", name: "Malta", region: "Europe", schengen: true },
  { code: "MD", name: "Moldova", region: "Europe" },
  { code: "MC", name: "Monaco", region: "Europe", rulesFrom: "SCHENGEN" },
  { code: "ME", name: "Montenegro", region: "Europe" },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe",
    schengen: true,
    aliases: ["Nederland", "Holland"],
    cities: ["Amsterdam"],
  },
  { code: "MK", name: "North Macedonia", region: "Europe", aliases: ["Macedonia"] },
  { code: "NO", name: "Norway", region: "Europe", schengen: true },
  { code: "PL", name: "Poland", region: "Europe", schengen: true },
  { code: "PT", name: "Portugal", region: "Europe", schengen: true },
  { code: "RO", name: "Romania", region: "Europe", schengen: true },
  { code: "RU", name: "Russia", region: "Europe", aliases: ["Russian Federation"] },
  { code: "SM", name: "San Marino", region: "Europe", rulesFrom: "SCHENGEN" },
  { code: "RS", name: "Serbia", region: "Europe" },
  { code: "SK", name: "Slovakia", region: "Europe", schengen: true },
  { code: "SI", name: "Slovenia", region: "Europe", schengen: true },
  { code: "ES", name: "Spain", region: "Europe", schengen: true, aliases: ["España"] },
  { code: "SE", name: "Sweden", region: "Europe", schengen: true },
  { code: "CH", name: "Switzerland", region: "Europe", schengen: true },
  { code: "UA", name: "Ukraine", region: "Europe" },
  {
    code: "GB",
    name: "United Kingdom",
    region: "Europe",
    aliases: ["UK", "Britain", "Great Britain", "England", "Scotland", "Wales", "Northern Ireland"],
  },
  { code: "VA", name: "Vatican City", region: "Europe", aliases: ["Vatican", "Holy See"], rulesFrom: "SCHENGEN" },
  { code: "FO", name: "Faroe Islands", region: "Europe", territoryOf: "DK" },
  { code: "GI", name: "Gibraltar", region: "Europe", territoryOf: "GB" },
  { code: "GL", name: "Greenland", region: "Europe", territoryOf: "DK" },
  { code: "GG", name: "Guernsey", region: "Europe", territoryOf: "GB" },
  { code: "IM", name: "Isle of Man", region: "Europe", territoryOf: "GB" },
  { code: "JE", name: "Jersey", region: "Europe", territoryOf: "GB" },
  { code: "SJ", name: "Svalbard", region: "Europe", territoryOf: "NO" },

  // North Africa
  { code: "DZ", name: "Algeria", region: "North Africa" },
  { code: "EG", name: "Egypt", region: "North Africa" },
  { code: "LY", name: "Libya", region: "North Africa" },
  { code: "MA", name: "Morocco", region: "North Africa" },
  { code: "SD", name: "Sudan", region: "North Africa" },
  { code: "TN", name: "Tunisia", region: "North Africa" },

  // West Africa
  { code: "BJ", name: "Benin", region: "West Africa" },
  { code: "BF", name: "Burkina Faso", region: "West Africa" },
  { code: "CV", name: "Cabo Verde", region: "West Africa", aliases: ["Cape Verde"] },
  { code: "CI", name: "Côte d'Ivoire", region: "West Africa", aliases: ["Ivory Coast"] },
  { code: "GM", name: "Gambia", region: "West Africa", aliases: ["The Gambia"] },
  { code: "GH", name: "Ghana", region: "West Africa" },
  { code: "GN", name: "Guinea", region: "West Africa" },
  { code: "GW", name: "Guinea-Bissau", region: "West Africa" },
  { code: "LR", name: "Liberia", region: "West Africa" },
  { code: "ML", name: "Mali", region: "West Africa" },
  { code: "MR", name: "Mauritania", region: "West Africa" },
  { code: "NE", name: "Niger", region: "West Africa" },
  { code: "NG", name: "Nigeria", region: "West Africa" },
  { code: "SN", name: "Senegal", region: "West Africa" },
  { code: "SL", name: "Sierra Leone", region: "West Africa" },
  { code: "TG", name: "Togo", region: "West Africa" },

  // Central Africa
  { code: "CM", name: "Cameroon", region: "Central Africa" },
  { code: "CF", name: "Central African Republic", region: "Central Africa" },
  { code: "TD", name: "Chad", region: "Central Africa" },
  { code: "CG", name: "Republic of the Congo", region: "Central Africa", aliases: ["Congo", "Congo-Brazzaville"] },
  {
    code: "CD",
    name: "DR Congo",
    region: "Central Africa",
    aliases: ["Democratic Republic of the Congo", "DRC", "Congo-Kinshasa"],
  },
  { code: "GQ", name: "Equatorial Guinea", region: "Central Africa" },
  { code: "GA", name: "Gabon", region: "Central Africa" },
  { code: "ST", name: "São Tomé and Príncipe", region: "Central Africa" },

  // East Africa
  { code: "BI", name: "Burundi", region: "East Africa" },
  { code: "KM", name: "Comoros", region: "East Africa" },
  { code: "DJ", name: "Djibouti", region: "East Africa" },
  { code: "ER", name: "Eritrea", region: "East Africa" },
  { code: "ET", name: "Ethiopia", region: "East Africa" },
  { code: "KE", name: "Kenya", region: "East Africa" },
  { code: "MG", name: "Madagascar", region: "East Africa" },
  { code: "MU", name: "Mauritius", region: "East Africa" },
  { code: "RW", name: "Rwanda", region: "East Africa" },
  { code: "SC", name: "Seychelles", region: "East Africa" },
  { code: "SO", name: "Somalia", region: "East Africa" },
  { code: "SS", name: "South Sudan", region: "East Africa" },
  { code: "TZ", name: "Tanzania", region: "East Africa" },
  { code: "UG", name: "Uganda", region: "East Africa" },
  { code: "RE", name: "Réunion", region: "East Africa", territoryOf: "FR" },
  { code: "YT", name: "Mayotte", region: "East Africa", territoryOf: "FR" },

  // Southern Africa
  { code: "AO", name: "Angola", region: "Southern Africa" },
  { code: "BW", name: "Botswana", region: "Southern Africa" },
  { code: "SZ", name: "Eswatini", region: "Southern Africa", aliases: ["Swaziland"] },
  { code: "LS", name: "Lesotho", region: "Southern Africa" },
  { code: "MW", name: "Malawi", region: "Southern Africa" },
  { code: "MZ", name: "Mozambique", region: "Southern Africa" },
  { code: "NA", name: "Namibia", region: "Southern Africa" },
  { code: "ZA", name: "South Africa", region: "Southern Africa" },
  { code: "ZM", name: "Zambia", region: "Southern Africa" },
  { code: "ZW", name: "Zimbabwe", region: "Southern Africa" },

  // North America
  { code: "CA", name: "Canada", region: "North America" },
  { code: "MX", name: "Mexico", region: "North America" },
  {
    code: "US",
    name: "United States",
    region: "North America",
    aliases: ["USA", "US", "America", "United States of America"],
  },
  { code: "BM", name: "Bermuda", region: "North America", territoryOf: "GB" },

  // Central America
  { code: "BZ", name: "Belize", region: "Central America" },
  { code: "CR", name: "Costa Rica", region: "Central America" },
  { code: "SV", name: "El Salvador", region: "Central America" },
  { code: "GT", name: "Guatemala", region: "Central America" },
  { code: "HN", name: "Honduras", region: "Central America" },
  { code: "NI", name: "Nicaragua", region: "Central America" },
  { code: "PA", name: "Panama", region: "Central America" },

  // Caribbean
  { code: "AG", name: "Antigua and Barbuda", region: "Caribbean" },
  { code: "BS", name: "Bahamas", region: "Caribbean", aliases: ["The Bahamas"] },
  { code: "BB", name: "Barbados", region: "Caribbean" },
  { code: "CU", name: "Cuba", region: "Caribbean" },
  { code: "DM", name: "Dominica", region: "Caribbean" },
  { code: "DO", name: "Dominican Republic", region: "Caribbean" },
  { code: "GD", name: "Grenada", region: "Caribbean" },
  { code: "HT", name: "Haiti", region: "Caribbean" },
  { code: "JM", name: "Jamaica", region: "Caribbean" },
  { code: "KN", name: "Saint Kitts and Nevis", region: "Caribbean" },
  { code: "LC", name: "Saint Lucia", region: "Caribbean" },
  { code: "VC", name: "Saint Vincent and the Grenadines", region: "Caribbean" },
  { code: "TT", name: "Trinidad and Tobago", region: "Caribbean" },
  { code: "AI", name: "Anguilla", region: "Caribbean", territoryOf: "GB" },
  { code: "AW", name: "Aruba", region: "Caribbean", territoryOf: "NL" },
  { code: "BQ", name: "Caribbean Netherlands", region: "Caribbean", territoryOf: "NL" },
  { code: "VG", name: "British Virgin Islands", region: "Caribbean", territoryOf: "GB" },
  { code: "KY", name: "Cayman Islands", region: "Caribbean", territoryOf: "GB" },
  { code: "CW", name: "Curaçao", region: "Caribbean", territoryOf: "NL" },
  { code: "GP", name: "Guadeloupe", region: "Caribbean", territoryOf: "FR" },
  { code: "MQ", name: "Martinique", region: "Caribbean", territoryOf: "FR" },
  { code: "MS", name: "Montserrat", region: "Caribbean", territoryOf: "GB" },
  { code: "PR", name: "Puerto Rico", region: "Caribbean", territoryOf: "US", rulesFrom: "US" },
  { code: "BL", name: "Saint Barthélemy", region: "Caribbean", territoryOf: "FR" },
  { code: "MF", name: "Saint Martin", region: "Caribbean", territoryOf: "FR" },
  { code: "SX", name: "Sint Maarten", region: "Caribbean", territoryOf: "NL" },
  { code: "TC", name: "Turks and Caicos Islands", region: "Caribbean", territoryOf: "GB" },
  { code: "VI", name: "US Virgin Islands", region: "Caribbean", territoryOf: "US", rulesFrom: "US" },

  // South America
  { code: "AR", name: "Argentina", region: "South America" },
  { code: "BO", name: "Bolivia", region: "South America" },
  { code: "BR", name: "Brazil", region: "South America", aliases: ["Brasil"], cities: ["Rio de Janeiro", "São Paulo"] },
  { code: "CL", name: "Chile", region: "South America" },
  { code: "CO", name: "Colombia", region: "South America" },
  { code: "EC", name: "Ecuador", region: "South America" },
  { code: "GY", name: "Guyana", region: "South America" },
  { code: "PY", name: "Paraguay", region: "South America" },
  { code: "PE", name: "Peru", region: "South America" },
  { code: "SR", name: "Suriname", region: "South America" },
  { code: "UY", name: "Uruguay", region: "South America" },
  { code: "VE", name: "Venezuela", region: "South America" },
  { code: "FK", name: "Falkland Islands", region: "South America", territoryOf: "GB" },
  { code: "GF", name: "French Guiana", region: "South America", territoryOf: "FR" },

  // Oceania
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "FJ", name: "Fiji", region: "Oceania" },
  { code: "KI", name: "Kiribati", region: "Oceania" },
  { code: "MH", name: "Marshall Islands", region: "Oceania" },
  { code: "FM", name: "Micronesia", region: "Oceania" },
  { code: "NR", name: "Nauru", region: "Oceania" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "PW", name: "Palau", region: "Oceania" },
  { code: "PG", name: "Papua New Guinea", region: "Oceania" },
  { code: "WS", name: "Samoa", region: "Oceania" },
  { code: "SB", name: "Solomon Islands", region: "Oceania" },
  { code: "TO", name: "Tonga", region: "Oceania" },
  { code: "TV", name: "Tuvalu", region: "Oceania" },
  { code: "VU", name: "Vanuatu", region: "Oceania" },
  { code: "AS", name: "American Samoa", region: "Oceania", territoryOf: "US" },
  { code: "CK", name: "Cook Islands", region: "Oceania", territoryOf: "NZ" },
  { code: "PF", name: "French Polynesia", region: "Oceania", territoryOf: "FR" },
  { code: "GU", name: "Guam", region: "Oceania", territoryOf: "US" },
  { code: "NC", name: "New Caledonia", region: "Oceania", territoryOf: "FR" },
  { code: "MP", name: "Northern Mariana Islands", region: "Oceania", territoryOf: "US" },
  { code: "NU", name: "Niue", region: "Oceania", territoryOf: "NZ" },
];
